tipos1:
	gcc tipos1.c -o tipos1

tipos2:
	gcc tipos2.c -o tipos2

tipos3:
	gcc tipos3.c -o tipos3

tipos4:
	gcc tipos4.c -o tipos4

tipos5:
	gcc tipos5.c -o tipos5

clean:
	rm tipos1 tipos2 tipos3 tipos4 tipos5

/*tipos4: tipos4.o
	ld -o tipos4 tipos4.o

tipos4.o: tipos4.s
	as -g -o tipos4.o tipos4.s

clean:
	rm tipos4 tipos4.o
*/
